# WARNING: this file is not suitable for production, please use with caution
version: '3'

services:
  api:
    image: flack
    build:
      context: .
      dockerfile: ./flack/deploy/Dockerfile
    command: python manage.py runserver
    volumes:
      - ./flack:/code/flack
      - ./db/:/db/
    ports:
      - "15000:5000"

  rabbitmq:
    image: rabbitmq
    ports:
      - "15672:5672"

  celery:
    image: flack
    build:
      context: .
      dockerfile: ./flack/deploy/Dockerfile
    command: python manage.py celery
    volumes:
      - ./flack:/code/flack
    depends_on:
      - api
      - rabbitmq

  neo4j:
    image: neo4j:latest
    ports:
      - "7687:7687"
      - "17474:7474"

  tests:
    image: flack
    build:
      context: .
      dockerfile: ./flack/deploy/Dockerfile
    command: "python -m unittest tests -vvv"
    volumes:
      - ./flack:/code/flack
      - ./tests:/code/tests
      - ./src:/code/src
    depends_on:
      - api
      - celery
      - rabbitmq
      - neo4j